import { Container } from "react-bootstrap";
import SiteLicense from "/LICENSE";

{/* Generated by https://creativecommons.org/choose/ */}
const ccAttribution = `
  <li xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/">
    <a property="dct:title" rel="cc:attributionURL" href="https://www.deviantart.com/snowfleikun/art/Dots-world-map-179891314">Dots world map</a> 
    by 
    <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://www.deviantart.com/snowfleikun">sNowFleikuN</a> 
    is licensed under 
    <a href="https://creativecommons.org/licenses/by/3.0/" target="_blank" rel="license noopener noreferrer" style="display: inline-block">
      CC BY 3.0
      <img style="height: 22px; margin-left: 3px; vertical-align: text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt="Creative Commons icon"/>
      <img style="height: 22px; margin-left: 3px; vertical-align: text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt="Creative Commons BY icon"/>
    </a>
  </li>
`;


function Introduction() {
  return (
    <Container className="py-5">
      <h2 className="text-center fw-bold fs-1">Licenses</h2>

      <details>
      <summary className="fw-bold">Full license text and information</summary>
      <pre>
      {SiteLicense}
      </pre>
      </details>

      <h2>Summary</h2>

      <ul>
        <li>cs-2340-team-website is distributed under the <a href="https://github.com/thatrobotdev/cs-2340-team-website/blob/main/LICENSE">MIT License</a>.</li>
        <li>cs-2340-team-website was built using <a href="https://github.com/twbs/examples">Bootstrap Examples</a>, which is distributed under the <a href="https://github.com/twbs/examples/blob/main/LICENSE">MIT License.</a></li>
        
        <div dangerouslySetInnerHTML={{ __html: ccAttribution }} />
      </ul>
    </Container>
  );
};

export default Introduction;
